# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@docs"
plugins:
  - jekyll-remote-theme

# Project Information
title: "Packaging Recognizer"
description: "An image classification system that identifies and classifies daily object packaging into multiple categories including bottled water, milk cartons, snack chips, and other common consumer products."
url: "" # Leave empty if testing locally

# Author Details
author:
  name: "Mohammad Ashfaq Ur Rahman"
  email: "imashfaqfardin@gmail.com"
  location: "Bangladesh" # Optional

# Layout Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true