# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Project Information
title: "Packaging Recognizer"
description: "An image classification system that identifies and classifies daily object packaging into multiple categories including bottled water, milk cartons, snack chips, and other common consumer products."
url: "https://ashfaqfardin.github.io"
baseurl: "" # Keep empty if this is your main github.io repo

# Author Details
author:
  name: "Mohammad Ashfaq Ur Rahman"
  email: "imashfaqfardin@gmail.com"
  location: "Bangladesh"

# Layout Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "single" # 'single' is more reliable for Minimal Mistakes than 'page'
      author_profile: true