# Theme Settings
remote_theme: "mmistakes/minimal-mistakes" # Use the main theme branch
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

include: ["pkg_recognizer.html"]

# Project Information
title: "Packaging Recognizer"
description: "AI-powered image classification for consumer packaging."
url: "" 
locale: "en-US"

# Author Details
author:
  name: "Mohammad Ashfaq Ur Rahman"
  location: "Bangladesh"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:imashfaqfardin@gmail.com"

# Layout Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "single" # This tells Jekyll to use the theme's default layout
      author_profile: true