# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Project Information
title: "Packaging Recognizer"
description: "An image classification system that identifies and classifies consumer product packaging."
url: "https://ashfaqfardin.github.io" 
baseurl: "" # Ensure this is empty if the repo name is ashfaqfardin.github.io

# Author Details
author:
  name: "Mohammad Ashfaq Ur Rahman"
  email: "imashfaqfardin@gmail.com"
  location: "Bangladesh"

# Layout Settings
defaults:
  - scope:
      path: ""
    values:
      layout: "single" # Changed from 'page' to 'single' for better compatibility
      author_profile: true